Fixed bugs in vecLib support: accidental overwriting of CPPFLAGS and LDFLAGS, failure to update options variable.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3360,7 +3360,15 @@ fi
 
 
 
+#Switch testing language to C++
+ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
+
+all_options="videodisplay jpeg tiff ffmpeg toon lapack"
 
 
 ################################################################################
@@ -3368,7 +3376,6 @@ fi
 #  Some of my own M4 macros
 #
 
-all_options="videodisplay jpeg tiff ffmpeg toon lapack"
 
 ################################################################################
 #
@@ -3377,28 +3384,18 @@ all_options="videodisplay jpeg tiff ffmpeg toon lapack"
 
 if test "$host_vendor" = apple
 then
+	CPPFLAGS="$CPPFLAGS -I /sw/include -I/usr/X11R6/include"
+	LIBS="$LIBS -L/sw/lib"
 	{ echo "$as_me:$LINENO: Adding /sw to the build path." >&5
 echo "$as_me: Adding /sw to the build path." >&6;}
-	LIBS="$LIBS -L/sw/lib"
-	CPPFLAGS="$CPPFLAGS -I/sw/include"
 	{ echo "$as_me:$LINENO: Adding /usr/X11R6/include to the build path." >&5
 echo "$as_me: Adding /usr/X11R6/include to the build path." >&6;}
-	{ echo "$as_me:$LINENO: Although this seems to be automatic under OSX it only works for X11/*" >&5
-echo "$as_me: Although this seems to be automatic under OSX it only works for X11/*" >&not GL/*;}
-	CPPFLAGS="$CPPFLAGS -I/usr/X11R6/include"
 fi
 
 ################################################################################
 #
 #Check for numerics
 #
-
-#Switch testing language to C++
-ac_ext=cc
-ac_cpp='$CXXCPP $CPPFLAGS'
-ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
 echo
@@ -3511,10 +3508,75 @@ _ACEOF
 
 fi
 
+##################################################
+#
+# Check for BLAS and LAPACK support
+#
+lapack=no
+
+if test "$toon" = yes && test "$host_vendor" == apple
+then
+
+	save_LIBS="$LIBS"
+	save_CPPFLAGS="$CPPFLAGS"
+	CPPFLAGS="$CPPFLAGS -framework vecLib"
+	LIBS="$LIBS -framework vecLib"
 
 
+	echo "$as_me:$LINENO: checking vecLib framework" >&5
+echo $ECHO_N "checking vecLib framework... $ECHO_C" >&6
+	a=0
+	cat >conftest.$ac_ext <<_ACEOF
+#include <numerics.h>
+#include <SVD.h>
+int main(){Matrix<2> m;SVD<2> svdm(m);return 0;}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  a=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
 
-if test "$toon" = yes && test "$host_vendor" != apple
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+
+	if test x$a	= x1
+	then
+		echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+		lapack=yes
+		options="$options lapack"
+	else
+		echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+		LIBS="$save_LIBS"
+		CPPFLAGS="$save_CPPFLAGS"
+	fi
+fi
+
+
+if test "$toon" = yes && test "$lapack" = no
 then
 
 	#Check whether we need -lf2c or -lg2c
@@ -3600,7 +3662,6 @@ rm -f conftest.err conftest.$ac_objext \
 	echo "$as_me:$LINENO: result: $f2c" >&5
 echo "${ECHO_T}$f2c" >&6
 
-	lapack=no
 
 	if test "$f2c" = Missing
 	then
@@ -3789,64 +3850,6 @@ _ACEOF
 
 fi
 
-if test "$toon" = yes && test "$host_vendor" == apple
-then
-
-	save_LIBS="$LIBS"
-	save_CPPFLAGS="$CPPFLAGS"
-	CPPFLAGS="-framework vecLib"
-	LIBS="-framework vecLib"
-
-
-	echo "$as_me:$LINENO: checking vecLib framework" >&5
-echo $ECHO_N "checking vecLib framework... $ECHO_C" >&6
-	a=0
-	cat >conftest.$ac_ext <<_ACEOF
-#include <numerics.h>
-#include <SVD.h>
-int main(){Matrix<2> m;SVD<2> svdm(m);return 0;}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_cxx_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  a=1
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-
-	if test x$a	= x1
-	then
-		echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-	else
-		echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-		LIBS="$save_LIBS"
-		CPPFLAGS="$save_CPPFLAGS"
-	fi
-fi
 
 
 cvd_major=`echo $PACKAGE_VERSION | awk -F'\\\\.' '{print $1}'`
