Added preliminary support for -framework vecLib in OSX

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3514,7 +3514,7 @@ fi
 
 
 
-if test "$toon" = yes
+if test "$toon" = yes && test "$host_vendor" != apple
 then
 
 	#Check whether we need -lf2c or -lg2c
@@ -3787,6 +3787,62 @@ _ACEOF
 
 	fi
 
+else if test "$toon" = yes && test "$host_vendor" != apple
+
+	save_LIBS="$LIBS"
+	save_CPPFLAGS="$CPPFLAGS"
+	CPPFLAGS="-framework vecLib"
+	LIBS="-framework vecLib"
+
+
+	echo "$as_me:$LINENO: checking \"vecLib framework\"" >&5
+echo $ECHO_N "checking \"vecLib framework\"... $ECHO_C" >&6
+	a=0
+	cat >conftest.$ac_ext <<_ACEOF
+#include <numerics.h>
+#include <SVD.h>
+int main(){Matrix<2> m;SVD<2> svdm(m);return 0;}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  a=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+
+	if test x$a	= x1
+	then
+		echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	else
+		echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+		LIBS="$save_LIBS"
+		CPPFLAGS="$save_CPPFLAGS"
+	fi
 fi
 
 
