Added test for ffmpeg version >= 0.4.9

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5119,15 +5119,94 @@ _ACEOF
 
 fi
 
+
+echo "$as_me:$LINENO: checking for av_read_frame in -lavformat" >&5
+echo $ECHO_N "checking for av_read_frame in -lavformat... $ECHO_C" >&6
+if test "${ac_cv_lib_avformat_av_read_frame+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lavformat  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char av_read_frame ();
+int
+main ()
+{
+av_read_frame ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_avformat_av_read_frame=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_avformat_av_read_frame=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_avformat_av_read_frame" >&5
+echo "${ECHO_T}$ac_cv_lib_avformat_av_read_frame" >&6
+if test $ac_cv_lib_avformat_av_read_frame = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBAVFORMAT 1
+_ACEOF
+
+  LIBS="-lavformat $LIBS"
+
+fi
+ #only in >= 0.4.9
 	if test "$ac_cv_lib_avcodec_avcodec_open$ac_cv_lib_avformat_av_open_input_file" = yesyes
 	then
-		cat >>confdefs.h <<\_ACEOF
+		if test "$ac_cv_lib_avformat_av_read_frame" = yes
+		then
+			cat >>confdefs.h <<\_ACEOF
 #define CVD_HAVE_FFMPEG 1
 _ACEOF
 
-		have_ffmpeg=yes
+			have_ffmpeg=yes
 
-		options="$options ffmpeg"
+			options="$options ffmpeg"
+		else
+			echo "You have FFMPEG, but the version is too old. Version 0.4.9 or newer is required."
+		fi
 	fi
 fi
 
