Support for new FFMPEG (tested against the latest SVN version as of the date of this commit).
img_convert has been depracated in favour of the GPL only libswscale.

FFMPEG will only be compiled in if you use --enable-gpl. If you distribute
programs which use libCVD with ffmpeg, then they have to be GPL'd.

libCVD has an array of colourspace conversion functions, so it may be possible
to use them instead of libswscale. That would enable the use of FFMPEG under
libCVD with the LGPL license.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -863,6 +863,7 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-gpl            Allow the use of GPL libraries.
   --disable-ssefast9      Disable the probably OK SSE FAST-9 detector (debgging only)
   --disable-ssefast10     Disable the probably OK SSE FAST-10 detector (debgging only)
   --disable-ssefast12     Disable the probably OK SSE FAST-12 detector (debgging only)
@@ -5264,6 +5265,12 @@ echo
 echo -----------------------------------------------
 echo Checking for operating system specific features
 echo -----------------------------------------------
+
+# Check whether --enable-gpl or --disable-gpl was given.
+if test "${enable_gpl+set}" = set; then
+  enableval="$enable_gpl"
+
+fi;
 
 
 # Check whether --with-dvbuffer or --without-dvbuffer was given.
@@ -9743,18 +9750,13 @@ fi
 		save_CXXFLAGS="$CXXFLAGS"
 		a=
 
-	if test "$with_ffmpeg" != yes
+	if test "$enable_gpl" != no && test "$enable_gpl" != ""
 	then
-		LIBS="$LIBS -L $with_ffmpeg"
-	fi
-	if test "`$CXX -dumpversion`" = 4.1.0
-	then
-		CXXFLAGS="$CXXFLAGS -D__STDC_CONSTANT_MACROS"
-	fi
 
 
 
-for ac_header in ffmpeg/avcodec.h ffmpeg/avformat.h
+
+for ac_header in ffmpeg/avcodec.h ffmpeg/avformat.h ffmpeg/swscale.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -9898,12 +9900,176 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
   cat >>confdefs.h <<_ACEOF
 #define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
 _ACEOF
+ ffmpeg_old_headers=1
+fi
 
+done
+
+
+
+
+for ac_header in libavcodec/avcodec.h libavformat/avformat.h libswscale/swscale.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_cxx_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------ ##
+## Report this to the CVD lists.  ##
+## ------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+ ffmpeg_new_headers=1
 else
   a=1
 fi
 
 done
+
+
+
+		if test "$ffmpeg_old_headers" == 1 || test "$ffmpeg_new_headers" == 1
+		then
+			if test "$ffmpeg_old_headers" == 1
+			then
+				cat >>confdefs.h <<\_ACEOF
+#define CVD_INTERNAL_HAVE_FFMPEG_OLD_HEADERS 1
+_ACEOF
+
+			fi
 
 
 echo "$as_me:$LINENO: checking for main in -lavutil" >&5
@@ -10051,7 +10217,7 @@ else
   a=1
 fi
 
-	echo "$as_me:$LINENO: checking for av_read_frame in -lavformat" >&5
+			echo "$as_me:$LINENO: checking for av_read_frame in -lavformat" >&5
 echo $ECHO_N "checking for av_read_frame in -lavformat... $ECHO_C" >&6
 if test "${ac_cv_lib_avformat_av_read_frame+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -10196,6 +10362,106 @@ _ACEOF
 else
   a=1
 fi
+
+
+echo "$as_me:$LINENO: checking for sws_getContext in -lswscale" >&5
+echo $ECHO_N "checking for sws_getContext in -lswscale... $ECHO_C" >&6
+if test "${ac_cv_lib_swscale_sws_getContext+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lswscale  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char sws_getContext ();
+int
+main ()
+{
+sws_getContext ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_swscale_sws_getContext=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_swscale_sws_getContext=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_swscale_sws_getContext" >&5
+echo "${ECHO_T}$ac_cv_lib_swscale_sws_getContext" >&6
+if test $ac_cv_lib_swscale_sws_getContext = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBSWSCALE 1
+_ACEOF
+
+  LIBS="-lswscale $LIBS"
+
+else
+  a=1
+fi
+
+		else
+			a=1
+		fi
+	else
+		a=1
+		{ echo "$as_me:$LINENO: WARNING: FFMPEG currently requires the use of --enable-gpl" >&5
+echo "$as_me: WARNING: FFMPEG currently requires the use of --enable-gpl" >&2;}
+	fi
+	#if test "$with_ffmpeg" != yes
+	#then
+#		APPEND(LIBS, [-L $with_ffmpeg])
+#	fi
+#	if test "`$CXX -dumpversion`" = 4.1.0
+#	then
+#		APPEND(CXXFLAGS, -D__STDC_CONSTANT_MACROS)
+#	fi
+
+	#Old ffmpeg?
+	#AC_CHECK_HEADERS(ffmpeg/avcodec.h ffmpeg/avformat.h, [], [a=1])
+	#AC_CHECK_LIB(avutil, main, [], [a=1])
+	#AC_CHECK_LIB(avformat, av_open_input_file, [], [a=1])
+	#AC_CHECK_LIB(avformat, av_read_frame, [ffmpeg_recent=yes], [a=1]) #only in >= 0.4.9
+	#AC_CHECK_LIB(avcodec, avcodec_open, [], [a=1])
 
 
 
